apiVersion: apps/v1
kind: Deployment
metadata:
  name: stress-ng
  labels:
    app: stress-ng
spec:
  replicas: 3
  selector:
    matchLabels:
      app: stress-ng
  template:
    metadata:
      labels:
        app: stress-ng
    spec:
      containers:
      - name: stress-ng
        image: alexeiled/stress-ng
        args: ["--cpu", "4", "--cpu-method", "all", "--timeout", "0", "--vm", "2", "--vm-bytes", "33%", "--vm-method", "all"]