apiVersion: batch/v1
kind: Job
metadata:
  name: image-training-job-gpu
spec:
  template:
    metadata:
    spec:
      containers:
      - name: got-image-training-job-vk
        image: chzbrgr71/got-image-training:2.00-gpu
        command: ["python","retrain.py"]
        args:                
          - "--bottleneck_dir=/tmp/tensorflow/bottlenecks"
          - "--model_dir=/tmp/tensorflow/inception"
          - "--summaries_dir=/tf-output"
          - "--output_graph=/tf-output"
          - "--output_labels=/tf-output"
          - "--image_dir=/images"
          - "--saved_model_dir=/tf-output"
        env:
        - name: KUBE_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name               
      restartPolicy: Never
      nodeSelector:
        kubernetes.io/role: agent
        agentpool: gpunodepool
      tolerations:
      - key: "sku"
        operator: "Equal"
        value: "gpu"
        effect: "NoSchedule"        